### ISSUE TITLE
Causing Crashes upon reloading world, specifically in host and play.

### ISSUE THREAD

**Issue by TheSecondDiaryKeeper** [NotLe0n/BetterChests#1]
Me and my friends were doing a playthrough with this mod and kept getting the same error

`System.NullReferenceException: Object reference not set to an instance of an object.`

After doing more digging, we found that this was being caused by the BetterChests mod. I'll attach an entire log to sift through, but I believe it has something to do with UIs.
[client.log](https://github.com/NotLe0n/BetterChests/files/6361847/client.log)

**Comment by NotLe0n** [comment]
Thanks for reporting this crash! Turns out the client doesn't recieve chest information when the world loads. Fixed in v1.1.1.
